version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: house_production
      POSTGRES_USER:
      POSTGRES_PASSWORD:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
#  grafana:
#    image: grafana/grafana
#    volumes:
#      - grafana-storage:/var/lib/grafana
#    ports:
#      - "4000:3000"

volumes:
  postgres-data:
  apps_root:
#  grafana-storage:
