version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: house_production
      POSTGRES_USER:
      POSTGRES_PASSWORD:
  rails:
    image: sanchorubyroid/house:latest
    depends_on:
      - db
    ports:
      - "3000:3000"
#  grafana:
#    image: grafana/grafana
#    volumes:
#      - grafana-storage:/var/lib/grafana
#    ports:
#      - "4000:3000"

volumes:
  postgres-data:
#  grafana-storage:
