<% dockerized = ENV["DOCKERIZED"].present? %>

default: &default
  username: <%= Rails.application.credentials.database[dockerized ? :production : :development][:username] %>
  password: <%= Rails.application.credentials.database[dockerized ? :production : :development][:password] %>
  host: <%= dockerized ? Rails.application.credentials.database[:production][:host] : "127.0.0.1" %>
  database: <%= dockerized ? "house_production" : "house_development" %>
  adapter: postgresql
  encoding: utf8
  pool: 30
  port: <%= ENV["DB_PORT"] || 5432 %>

development: &development
  <<: *default

test:
  <<: *default
  database: "house_test"

production:
  <<: *default
