:concurrency: 5
:logfile: ./log/sidekiq.log
:queues:
  - default
  - house_app_development_default
  - house_app_production_default

#:schedule:
#  copart_hourly_routine_job:
#    cron: '0 55 */1 * * *'   # Runs every 1 hour at 55 minutes
#    class: "::Copart::HourlyRoutineJob"

#  copart_ten_minutes_routine_job:
#      cron: '0 */10 * * * *'   # Runs every 10 minutes
#      class: "::Copart::TenMinutesRoutineJob"
